name: smart_tip
description: A customizable tooltip package for Flutter using flutter_hooks.
version: 0.0.1
# homepage: https://github.com/your_username/smart_tip
# repository: https://github.com/your_username/smart_tip
# issue_tracker: https://github.com/your_username/smart_tip/issues

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


 